'use client';

import { useApp } from '@/context/AppContext';

export default function RefundsPage() {
  const { lang } = useApp();

  const content = {
    en: {
      title: 'Refund & SLA Policy',
      updated: 'Last updated: May 2026',
      intro: 'Because AuraTV provisions database accounts and issues digital cryptographic stream configurations instantly upon payment verification, we maintain transparent guidelines regarding transaction reversals.',
      sections: [
        { title: '1. Trial Allocations', text: 'Our 24-Hour Trial tier functions as a complete technical validation phase. Since this tier is designed to test your hardware interface and internet connection routing against our media indexes prior to larger commitments, it is non-refundable.' },
        { title: '2. Monthly Account Claims', text: 'If you experience system access failure or direct protocol downtime that is verified to stem from our server distribution core, you are fully entitled to a complete technical refund within the first 7 days of your billing cycle. To request processing, submit an inquiry via our DevOps validation endpoints.' },
        { title: '3. Digital Product Exclusions', text: 'Refund requests generated by local connection bandwidth limitations or third-party IPTV application software glitches are excluded from standard transaction reversals. We highly encourage utilizing the free or test layers before purchasing monthly access.' }
      ]
    },
    es: {
      title: 'Política de Reembolsos y SLA',
      updated: 'Última actualización: Mayo 2026',
      intro: 'Debido a que AuraTV aprovisiona cuentas y emite configuraciones criptográficas digitales de forma instantánea tras la verificación del pago, mantenemos pautas transparentes sobre reversiones.',
      sections: [
        { title: '1. Asignaciones de Prueba', text: 'Nuestro nivel de Prueba de 24 Horas funciona como una fase de validación técnica completa para probar su hardware y conexión de internet contra nuestros índices de medios antes de compromisos mayores, por lo que no es reembolsable.' },
        { title: '2. Reclamaciones de Cuentas Mensuales', text: 'Si experimenta una falla de acceso o un tiempo de inactividad verificado que provenga de nuestro núcleo de distribución, tiene derecho a un reembolso dentro de los primeros 7 días de su ciclo de facturación a través de nuestros puntos de contacto DevOps.' },
        { title: '3. Exclusiones de Productos Digitales', text: 'Las solicitudes generadas por limitaciones de ancho de banda local o fallas de software en aplicaciones de reproducción de terceros quedan excluidas de las reversiones estándar.' }
      ]
    }
  };

  const t = content[lang as 'en' | 'es'] || content.en;

  return (
    <div className="bg-[#f4f4f7] text-[#0a0a0c] dark:bg-[#060608] dark:text-[#f4f4f7] min-h-screen py-16 px-6 transition-colors duration-300">
      <main className="max-w-3xl mx-auto space-y-8 bg-white dark:bg-[#0c0c10] border border-black/5 dark:border-white/5 p-8 md:p-12 rounded-3xl shadow-sm">
        <div className="space-y-1">
          <h1 className="text-2xl md:text-4xl font-black tracking-tight">{t.title}</h1>
          <p className="text-xs text-gray-400 font-semibold">{t.updated}</p>
        </div>
        <p className="text-xs md:text-sm text-gray-500 dark:text-gray-400 leading-relaxed font-medium">{t.intro}</p>
        <div className="space-y-6 pt-4 border-t border-black/5 dark:border-white/5">
          {t.sections.map((sec, idx) => (
            <div key={idx} className="space-y-2">
              <h3 className="text-sm font-black text-violet-600 dark:text-violet-400">{sec.title}</h3>
              <p className="text-xs text-gray-500 dark:text-gray-300 leading-relaxed text-justify font-medium">{sec.text}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}